version: "3.8"

services:
  websocket-server:
    build: .
    container_name: websocket-server
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - /Users/subhajitchaudhury/Desktop/code-playground/projects/streamsync-backend:/app

    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
