version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - streamsync_backend

  streamsync-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamsync-server-compose
    depends_on:
      - redis
    ports:
      - "4000:4000"
    environment:
      WS_PORT: 4000
      SERVER_ID: streamsync-docker
      REDIS_URL: redis://redis:6379
    networks:
      - streamsync_backend

networks:
  streamsync_backend:
    driver: bridge
